##############################################################################
# Foundation training config — multi-morphology pretraining.
#
# Uses Gen_Env with a URDF catalog.  Actor has NO genome access.
##############################################################################

exp_name: 10_morph

training:
  num_envs: 16512
  max_iterations: 20
  eval_interval: 100

obs:
  add_genome_obs_actor: false
  add_genome_obs_critic: true

catalog:
  n_urdf: 192
  catalog_dir: null # Not needed anymore unless specified in the CLI
  urdf_seed: 11
